name: Android CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build --stacktrace

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest

      # Emulator setup
      - name: Set up Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          target: default
          arch: x86_64
          profile: pixel_5
          emulator-options: -no-window -gpu swiftshader_indirect -no-snapshot


      - name: Run Instrumented Tests
        run: ./gradlew connectedDebugAndroidTest
        continue-on-error: true

      - name: Upload Unit Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: junit-unit-test-reports
          path: app/build/reports/tests/testDebugUnitTest

      - name: Upload Instrumentation Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-instrumentation-test-reports
          path: app/build/reports/androidTests/connected
